name: todo_list
description: "A todo app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  intl: ^0.19.0
  fpdart: ^1.1.0
  path: ^1.9.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/background.jpeg
    - assets/images/cloud.jpeg